defaults:
  - dataset: trec
  - model: cnn

data_dir: data/${dataset.name}
dataset:
  rm_stopwords: False
  processed:
    train: ${data_dir}/processed_train.csv
    val: ${data_dir}/processed_val.csv
    test: ${data_dir}/processed_test.csv
    vocab: ${data_dir}/vocab.txt

word2vec_path: data/GoogleNews-vectors-negative300.bin
model_file: model/${dataset.name}_${model.name}.model
