name: mr

lowercase: True
raw:
  pos: ${data_dir}/rt-polarity.pos
  neg: ${data_dir}/rt-polarity.neg
fields:
  raw_text: text
  processed_text: processed_text
  seq_len: len
  label: label

num_classes: 2
type: pos_neg

train:
  # max_seq_len: 110
  num_classes: 2
  max_seq_len: 20
  batch_size: 50
  word_vec_dim: 300
