name: trec

lowercase: False
raw:
  train: ${data_dir}/train.csv
  test: ${data_dir}/test.csv
fields:
  raw_text: text
  processed_text: processed_text
  seq_len: len
  label: label-coarse

type: text_label

train:
  # max_seq_len: 110
  num_classes: 6
  max_seq_len: 10
  batch_size: 50
  word_vec_dim: 300
