name: cnn

hyperparams:
  learning_rate: 0.0001
  max_epochs: 20
  in_channels: 1
  out_channels: 16
  kernel_sizes:
    - 3
    - 4
    - 5
  cnn_stride: 1
  pooling_stride: 2
  dropouts:
    p1: 0.2
    p2: 0.5
  fc_features: 64
